apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fm-team-fm
  description: fm-team repo
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/fm-team
  lifecycle: experimental
